name: Build and run Pulsar4X tests

on:
  push:
    branches: [ AddGithubActionsTestReport ]
  pull_request:
    branches: [ AddGithubActionsTestReport ]

jobs:
  windows-server-2022:
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      - name: Build
        shell: pwsh
        run: |
          cd Pulsar4X
          dotnet restore "Pulsar4X.sln"
          dotnet build --no-restore
          
      - name: Run tests
        uses: zyborg/dotnet-tests-report@v1
        with:
          project_path: Pulsar4X/Pulsar4X.Tests
          report_name: Pulsar4X_Tests
          report_title: Pulsar4X Tests on windows
#        github_token: ${{ secrets.GITHUB_TOKEN }}
                
#      - name: Run tests
#        shell: pwsh
#        run: |
#          cd Pulsar4X
#          dotnet test --no-restore

  ubuntu-22:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x

    - name: Build
      shell: bash
      run: |
        cd Pulsar4X
        dotnet restore "Pulsar4X.sln"
        dotnet build --no-restore
          
    - name: Run tests
      shell: bash
      run: |
        cd Pulsar4X
        dotnet test --no-restore
  
  macOS-12:
    runs-on: macos-12
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x

    - name: Build
      shell: bash
      run: |
        cd Pulsar4X
        dotnet restore "Pulsar4X.sln"
        dotnet build --no-restore
          
    - name: Run tests
      shell: bash
      run: |
        cd Pulsar4X
        dotnet test --no-restore